Update component-pre-uninstall-check.yaml

diff --git a/charts/canvas-oda/templates/component-pre-uninstall-check.yaml b/charts/canvas-oda/templates/component-pre-uninstall-check.yaml
--- a/charts/canvas-oda/templates/component-pre-uninstall-check.yaml
+++ b/charts/canvas-oda/templates/component-pre-uninstall-check.yaml
@@ -1,30 +1,26 @@
-apiVersion: batch/v1
-kind: Job
+apiVersion: v1
+kind: Pod
 metadata:
-  name: pre-uninstall-component-check
+  name: pre-delete-component-check
   namespace: {{ .Release.Namespace }}
   annotations:
-    "helm.sh/hook" : pre-delete
-    "helm.sh/weight" : "0"
+    "helm.sh/hook": pre-delete
     "helm.sh/hook-delete-policy": hook-succeeded
 spec:
-  template:
-    spec:
-      serviceAccountName: odacomponent-account
-      containers:
-        - name: component-checker
-          image: bitnami/kubectl:latest
-          command:
-            - /bin/sh
-            - -c
-            - |
-              echo "Checking for component Custom Resources (CRs) in the canvas cluster..."
-              if [ $(kubectl get components.oda.tmforum.org -A | wc -l) -gt 1 ]; then
-                echo "Error: Uninstallation aborted as below components present."
-                kubectl get components.oda.tmforum.org -A
-                exit 1  #Prevent Helm from proceeding
-              else
-                echo "No component CRs found. Proceeding with uninstallation."
-              fi
-      restartPolicy: Never
-  backoffLimit: 1
+  restartPolicy: Never
+  containers:
+    - name: check-components
+      image: bitnami/kubectl:latest
+      command:
+        - /bin/sh
+        - -c
+        - |
+          echo "Checking for component Custom Resources (CRs) in the cluster..."
+          COMPONENT_COUNT=$(kubectl get components.oda.tmforum.org -A --no-headers | wc -l)
+          if [ "$COMPONENT_COUNT" -gt 0 ]; then
+            echo "Error: Uninstallation aborted as components are present in the cluster."
+            kubectl get components.oda.tmforum.org -A
+            exit 1  # Exit to prevent Helm from proceeding
+          else
+            echo "No component CRs found. Proceeding with uninstallation."
+          fi
