Update temp-release-combined.yml

diff --git a/.github/workflows/temp-release-combined.yml b/.github/workflows/temp-release-combined.yml
--- a/.github/workflows/temp-release-combined.yml
+++ b/.github/workflows/temp-release-combined.yml
@@ -129,6 +129,11 @@ jobs:
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
+
+  check-new-release:
+    runs-on: ubuntu-latest
+    needs: release-api-gateway
+    steps:
       - name: Install kubectl
         run: |
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
@@ -175,6 +180,41 @@ jobs:
          kubectl create namespace istio-ingress
          kubectl label namespace istio-ingress istio-injection=enabled
          helm install istio-ingress istio/gateway -n istio-ingress --set labels.app=istio-ingress --set labels.istio=ingressgateway
+
+      - name: Install Helm chart from Git repo
+        run: |
+          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway 
+          helm repo update
+          helm install canvas oda-canvas-api-gateway/canvas-oda -n canvas --create-namespace 
+
+      - name: Check if deployment was successful
+        run: |
+          if kubectl get pods -n canvas | grep -q "Running"; then
+            echo "Helm installation and deployment successful. All pods are running."
+          else
+            echo "Error: Deployment failed. Not all pods are running."
+            exit 1
+          fi
+  
+      - name: Port Forwarding Keycloak Service
+        run: |
+          sleep 30
+          kubectl -n canvas port-forward svc/canvas-keycloak 8083:8083 &
+  
+      - name: Installing components PC & PI
+        run: |
+          helm repo add oda-components https://tmforum-oda.github.io/reference-example-components/
+          helm install pc oda-components/productcatalog -n components
+  
+      - name: Check status of deployments
+        run: |
+          sleep 90
+          kubectl get all -n canvas
+          kubectl get all -n components
+          kubectl get all -n istio-ingress
+          kubectl get all -n istio-system
+          kubectl get exposedapis -n components
+          kubectl get components -n components
 
 
       
