Update temporary-combinedrelease.yml

diff --git a/.github/workflows/temporary-combinedrelease.yml b/.github/workflows/temporary-combinedrelease.yml
--- a/.github/workflows/temporary-combinedrelease.yml
+++ b/.github/workflows/temporary-combinedrelease.yml
@@ -113,18 +113,10 @@ jobs:
         run: |
           cd ./charts/canvas-api-gateway/combined-api-gateway-chart
           helm dependency update
-
-          # Update dependencies for apisix-gateway chart
           cd apisix-gateway
           helm dependency update
-
-          # Update dependencies for kong-gateway chart
           cd ../kong-gateway
           helm dependency update
-
-          # Return to the base directory and list files
-          cd ../
-          ls -la
           helm dependency update
 
       - name: Run chart-releaser for API Gateway
@@ -133,33 +125,139 @@ jobs:
           charts_dir: ./charts/canvas-api-gateway
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-          
-  confirm-api-gateway-release:
+
+
+  check-new-release:
     runs-on: ubuntu-latest
     needs: release-api-gateway
     steps:
-      - name: Confirm API Gateway charts were released properly
+      - name: Install kubectl
         run: |
-          # Add the required Helm repository
+          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
+          kubectl version --client
+          uname -m
+  
+      - name: Install kind
+        run: |
+          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
+          chmod +x ./kind
+          sudo mv ./kind /usr/local/bin/kind
+  
+      - name: Create kind cluster
+        run: |
+          kind create cluster
+          kubectl get nodes --show-labels
+          
+      - name: Download Kind LB Cloud Provider
+        run: |
+         git clone https://github.com/kubernetes-sigs/cloud-provider-kind.git
+         cd cloud-provider-kind && make
+         bin/cloud-provider-kind &
+  
+      - name: Install Helm
+        run: |
+          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+          chmod 700 get_helm.sh
+          ./get_helm.sh
+          kubectl get ns
+  
+      - name: Install helm-git
+        run: |
+          helm plugin install https://github.com/aslafy-z/helm-git.git
+  
+      - name: Install istio Helm chart
+        run: |
+         helm repo add istio https://istio-release.storage.googleapis.com/charts
+         helm repo update
+         kubectl create namespace istio-system
+         helm install istio-base istio/base -n istio-system
+         helm install istiod istio/istiod -n istio-system --wait
+         kubectl create namespace istio-ingress
+         kubectl label namespace istio-ingress istio-injection=enabled
+         helm install istio-ingress istio/gateway -n istio-ingress --set labels.app=istio-ingress --set labels.istio=ingressgateway
+
+      - name: Install Helm chart from Git repo
+        run: |
           helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway
           helm repo update
+          helm install canvas oda-canvas-api-gateway/canvas-oda -n canvas --create-namespace --devel
 
-          # Check for the latest version of the apisix-gateway chart
-          latest_apisix_gateway=$(helm search repo oda-canvas-api-gateway/apisix-gateway --versions | awk 'NR==2 {print $2}')
-          if [ -z "$latest_apisix_gateway" ]; then
-            echo "Error: apisix-gateway chart release was not successful."
+      - name: Check if deployment was successful
+        run: |
+          if kubectl get pods -n canvas | grep -q "Running"; then
+            echo "Helm installation and deployment successful. All pods are running."
+          else
+            echo "Error: Deployment failed. Not all pods are running."
+            exit 1
+          fi
+  
+      - name: Port Forwarding Keycloak Service
+        run: |
+          sleep 30
+          kubectl -n canvas port-forward svc/canvas-keycloak 8083:8083 &
+  
+      - name: Installing components PC & PI
+        run: |
+          helm repo add oda-components https://tmforum-oda.github.io/reference-example-components/
+          helm install pc oda-components/productcatalog -n components
+  
+      - name: Check status of deployments
+        run: |
+          echo "Waiting for resources to be ready..."
+          sleep 90
+          LOG_FILE="/tmp/kubernetes_status.log"
+          HELM_LOG_FILE="/tmp/helm_installation.log"
+          echo "Current Kubernetes context:" | tee -a "$LOG_FILE"
+          kubectl config current-context | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'canvas' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n canvas | tee -a "$LOG_FILE" || echo "No resources found in 'canvas' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n components | tee -a "$LOG_FILE" || echo "No resources found in 'components' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'istio-ingress' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n istio-ingress | tee -a "$LOG_FILE" || echo "No resources found in 'istio-ingress' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'istio-system' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n istio-system | tee -a "$LOG_FILE" || echo "No resources found in 'istio-system' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching ExposedAPIs in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get exposedapis -n components | tee -a "$LOG_FILE" || echo "No ExposedAPIs found in 'components' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching components in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get components -n components | tee -a "$LOG_FILE" || echo "No components found in 'components' namespace." | tee -a "$LOG_FILE"
+          helm list --all-namespaces | tee "$HELM_LOG_FILE"
+
+      - name: Upload Test Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report
+          path: |
+            /tmp/helm_installation.log
+            /tmp/kubernetes_status.log
+  
+      - name: Delete kind cluster
+        if: always()
+        run: |
+          kind delete cluster
+        
+      - name: Check Kubernetes resource status
+        run: |
+          LOG_FILE="/tmp/kubernetes_status.log"
+          echo "Checking the entire Kubernetes log for failures..."
+          
+          if grep -i -E 'failed|CrashLoopBackOff|error' "$LOG_FILE"; then
+            echo "There are Kubernetes resource failures!"
             exit 1
           else
-            echo "apisix-gateway chart released successfully. Version: $latest_apisix_gateway"
+            echo "OK, no Kubernetes resource failures."
           fi
 
-          # Check for the latest version of the kong-gateway chart
-          latest_kong_gateway=$(helm search repo oda-canvas-api-gateway/kong-gateway --versions | awk 'NR==2 {print $2}')
-          if [ -z "$latest_kong_gateway" ]; then
-            echo "Error: kong-gateway chart release was not successful."
+      - name: Check Helm installation status
+        run: |
+          HELM_LOG_FILE="/tmp/helm_installation.log"
+          echo "Checking the entire Helm log for failures..."
+          
+          if grep -i -E 'failed|error' "$HELM_LOG_FILE"; then
+            echo "There are Helm installation failures!"
             exit 1
           else
-            echo "kong-gateway chart released successfully. Version: $latest_kong_gateway"
+            echo "OK, no Helm installation failures."
           fi
-
-          echo "All API Gateway charts released successfully."
