Update temp-release-combined.yml

diff --git a/.github/workflows/temp-release-combined.yml b/.github/workflows/temp-release-combined.yml
--- a/.github/workflows/temp-release-combined.yml
+++ b/.github/workflows/temp-release-combined.yml
@@ -183,7 +183,7 @@ jobs:
 
       - name: Install Helm chart from Git repo
         run: |
-          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway 
+          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway --devel
           helm repo update
           helm install canvas oda-canvas-api-gateway/canvas-oda -n canvas --create-namespace 
 
@@ -210,20 +210,59 @@ jobs:
         run: |
           echo "Waiting for resources to be ready..."
           sleep 90
-          echo "Current Kubernetes context:"
-          kubectl config current-context
-          echo "Fetching resources in the 'canvas' namespace:"
-          kubectl get all -n canvas || echo "No resources found in 'canvas' namespace."
-          echo "Fetching resources in the 'components' namespace:"
-          kubectl get all -n components || echo "No resources found in 'components' namespace."
-          echo "Fetching resources in the 'istio-ingress' namespace:"
-          kubectl get all -n istio-ingress || echo "No resources found in 'istio-ingress' namespace."
-          echo "Fetching resources in the 'istio-system' namespace:"
-          kubectl get all -n istio-system || echo "No resources found in 'istio-system' namespace."
-          echo "Fetching ExposedAPIs in the 'components' namespace:"
-          kubectl get exposedapis -n components || echo "No ExposedAPIs found in 'components' namespace."
-          echo "Fetching components in the 'components' namespace:"
-          kubectl get components -n components || echo "No components found in 'components' namespace."
+          LOG_FILE="/tmp/kubernetes_status.log"
+          HELM_LOG_FILE="/tmp/helm_installation.log"
+          echo "Current Kubernetes context:" | tee -a "$LOG_FILE"
+          kubectl config current-context | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'canvas' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n canvas | tee -a "$LOG_FILE" || echo "No resources found in 'canvas' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n components | tee -a "$LOG_FILE" || echo "No resources found in 'components' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'istio-ingress' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n istio-ingress | tee -a "$LOG_FILE" || echo "No resources found in 'istio-ingress' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching resources in the 'istio-system' namespace:" | tee -a "$LOG_FILE"
+          kubectl get all -n istio-system | tee -a "$LOG_FILE" || echo "No resources found in 'istio-system' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching ExposedAPIs in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get exposedapis -n components | tee -a "$LOG_FILE" || echo "No ExposedAPIs found in 'components' namespace." | tee -a "$LOG_FILE"
+          echo "Fetching components in the 'components' namespace:" | tee -a "$LOG_FILE"
+          kubectl get components -n components | tee -a "$LOG_FILE" || echo "No components found in 'components' namespace." | tee -a "$LOG_FILE"
+          helm list --all-namespaces | tee "$HELM_LOG_FILE"
 
 
-      
+                
+      - name: Upload Test Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report
+          path: |
+           /tmp/helm_installation.log
+           /tmp/kubernetes_status.log
+	  
+      - name: Delete kind cluster
+        if: always()
+        run: |
+          kind delete cluster
+          
+      - name: Check Kubernetes resource status
+        run: |
+          LOG_FILE="/tmp/kubernetes_status.log"
+          echo "Checking the entire Kubernetes log for failures..."
+          
+          if grep -i -E 'failed|CrashLoopBackOff|error' "$LOG_FILE"; then
+            echo "There are Kubernetes resource failures!"
+            exit 1
+          else
+            echo "OK, no Kubernetes resource failures."
+          fi
+
+      - name: Check Helm installation status
+        run: |
+          HELM_LOG_FILE="/tmp/helm_installation.log"
+          echo "Checking the entire Helm log for failures..."
+          
+          if grep -i -E 'failed|error' "$HELM_LOG_FILE"; then
+            echo "There are Helm installation failures!"
+            exit 1
+          else
+            echo "OK, no Helm installation failures."
+          fi
