Update temporary-combinedrelease.yml

diff --git a/.github/workflows/temporary-combinedrelease.yml b/.github/workflows/temporary-combinedrelease.yml
--- a/.github/workflows/temporary-combinedrelease.yml
+++ b/.github/workflows/temporary-combinedrelease.yml
@@ -49,59 +49,55 @@ jobs:
           charts_dir: ./charts
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-      
-      # Adding a sleep delay after releasing charts
+
       - name: Sleep for 60 seconds
         run: sleep 60
 
-delay-for-canvas-chart-release:
-  runs-on: ubuntu-latest
-  needs: release-charts
-  steps:
-    - name: Confirm new release was done properly
-      run: |
-        # Add the required Helm repository
-        helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway
-        helm repo update
+  delay-for-canvas-chart-release:
+    runs-on: ubuntu-latest
+    needs: release-charts
+    steps:
+      - name: Confirm new release was done properly
+        run: |
+          # Add the required Helm repository
+          helm repo add oda-canvas-api-gateway https://rj-acc.github.io/oda-canvas-api-gateway
+          helm repo update
 
-        # Check for the latest version of the cert-manager-init chart
-        latest_cert_manager=$(helm search repo oda-canvas-api-gateway/cert-manager-init --versions | awk 'NR==2 {print $2}')
-        if [ -z "$latest_cert_manager" ]; then
-          echo "Error: cert-manager-init chart release was not successful."
-          exit 1
-        else
-          echo "cert-manager-init chart released successfully. Version: $latest_cert_manager"
-        fi
+          # Check for the latest version of the cert-manager-init chart
+          latest_cert_manager=$(helm search repo oda-canvas-api-gateway/cert-manager-init --versions | awk 'NR==2 {print $2}')
+          if [ -z "$latest_cert_manager" ]; then
+            echo "Error: cert-manager-init chart release was not successful."
+            exit 1
+          else
+            echo "cert-manager-init chart released successfully. Version: $latest_cert_manager"
+          fi
 
-        # Check for the latest version of the canvas-vault chart
-        latest_canvas_vault=$(helm search repo oda-canvas-api-gateway/canvas-vault --versions | awk 'NR==2 {print $2}')
-        if [ -z "$latest_canvas_vault" ]; then
-          echo "Error: canvas-vault chart release was not successful."
-          exit 1
-        else
-          echo "canvas-vault chart released successfully. Version: $latest_canvas_vault"
-        fi
+          # Check for the latest version of the canvas-vault chart
+          latest_canvas_vault=$(helm search repo oda-canvas-api-gateway/canvas-vault --versions | awk 'NR==2 {print $2}')
+          if [ -z "$latest_canvas_vault" ]; then
+            echo "Error: canvas-vault chart release was not successful."
+            exit 1
+          else
+            echo "canvas-vault chart released successfully. Version: $latest_canvas_vault"
+          fi
 
-        # Check for the latest version of the canvas-oda chart
-        latest_canvas_oda=$(helm search repo oda-canvas-api-gateway/canvas-oda --versions | awk 'NR==2 {print $2}')
-        if [ -z "$latest_canvas_oda" ]; then
-          echo "Error: canvas-oda chart release was not successful."
-          exit 1
-        else
-          echo "canvas-oda chart released successfully. Version: $latest_canvas_oda"
-        fi
+          # Check for the latest version of the canvas-oda chart
+          latest_canvas_oda=$(helm search repo oda-canvas-api-gateway/canvas-oda --versions | awk 'NR==2 {print $2}')
+          if [ -z "$latest_canvas_oda" ]; then
+            echo "Error: canvas-oda chart release was not successful."
+            exit 1
+          else
+            echo "canvas-oda chart released successfully. Version: $latest_canvas_oda"
+          fi
 
-        echo "All charts released successfully."
+          echo "All charts released successfully."
 
-    # Adding a sleep delay after confirming canvas chart release
-    - name: Sleep for 60 seconds
-      run: sleep 60
+      - name: Sleep for 60 seconds
+        run: sleep 60
 
-
-      
   release-api-gateway:
     runs-on: ubuntu-latest
-    needs: delay-for-canvas-chart-release  # Ensures this job runs after 'release-charts and delay 60'
+    needs: delay-for-canvas-chart-release
     steps:
       - name: Checkout
         uses: actions/checkout@v3
